language: python
python: 2.7
env:
  - WINEENV=py27
before_install:
  - "./.travis-setup.sh"
install:
  - git clone https://github.com/boto/boto.git
  - /opt/wine-staging/bin/wine 'C:\Python27\Scripts\pip.exe' -r boto/requirements.txt
script: cd boto && /opt/wine-staging/bin/wine 'C:\Python27\Python.exe' tests/test.py default
