language: python
python: 2.7
env:
  - WINEENV=py27
before_install:
  - "./.travis-setup.sh"
install:
  - git clone https://github.com/zopefoundation/zope.interface.git
script: cd zope.interface && /opt/wine-staging/bin/wine 'C:\Python27\Python.exe' setup.py test
